version: "2"

services:
  node1:
    build: ./node.js
    links:
         - redis
    ports:
         - "8080"
    volumes:
         - ./node.js:/src
    networks:
        uln:
         ipv4_address: 10.8.0.3

  node2:
    build: ./node.js
    links:
         - redis
    volumes:
         - ./node.js:/src
    ports:
         - "8080"
    networks:
        uln:
         ipv4_address: 10.8.0.4

  node3:
    build: ./node.js
    links:
         - redis
    ports:
         - "8080"
    volumes:
         - ./node.js:/src
    networks:
        uln:
         ipv4_address: 10.8.0.5

  redis:
     image: redis:latest
     ports:
          - 6379:6379
     networks:
        uln:
         ipv4_address: 10.8.0.6

  nginx:
    build: ./nginx/
    ports:
            - "80:80"
    depends_on:
            - node1
            - node2 
            - node3
    links:
            - node1
            - node2
            - node3
    networks:
        uln:
         ipv4_address: 10.8.0.2

networks:
    uln:
     ipam:
        config:
         - subnet: 10.8.0.0/16
           ip_range: 10.8.0.0/24
